### ISSUE TITLE
Add Guide link in the header of Doges on Trial

### ISSUE THREAD

**Issue by federicoast** [kleros/doges-on-trial#32]
I think we should add a link to the pilot explainer in the header of the Doge interface:

https://medium.com/kleros/doges-on-trial-pilot-explainer-911492c3a7d8

Just as we did in the Juror interface. We could add it to the right of Jurors.

**Comment by epiqueras** [comment]
I think this would make the nav bar too big. Is it not enough that it's inside "How it Works"?

**Comment by clesaege** [comment]
Put in the how it works
