### ISSUE TITLE
Solve the images not displaying

### ISSUE THREAD

**Issue by clesaege** [kleros/doges-on-trial#41]
Once in a while (~25% of the times), only a few images load and not the rest.
Ticking or unticking filters generally solve the problem.

**Comment by epiqueras** [comment]
Any tips on how to replicate this? I can't seem to do it.

**Comment by firesofmay** [comment]
I have seen this too. It just gets stuck and I have to reselect the filters. Not sure of the steps. Will share if I find anyway.

**Comment by firesofmay** [comment]
@epiqueras This issue still persists. Check the video below:
https://youtu.be/5auaIk9ApxE

**Comment by firesofmay** [comment]
@epiqueras Reloaded and cleared cache multiple times, so yes. I just simulated it again in a new tab. Try doing the exact same filter selection as I did in the video. I am able to reproduce it again in prod.
