### ISSUE TITLE
Email notification sometimes contain "{{message}}" instead of actual body

### ISSUE THREAD

**Issue by firesofmay** [kleros/doges-on-trial#42]
Sometimes I don't see any content in the email notifications received.
Example screenshot attached below:

<img width="1180" alt="screen shot 2018-08-23 at 10 38 29 am" src="https://user-images.githubusercontent.com/889538/44505752-b5dea880-a6c0-11e8-97f8-dbf48e894a5d.png">

PS: I had challenged the following image. And in the dashboard now I see it in "Pending" state:
<img width="268" alt="screen shot 2018-08-23 at 10 35 08 am" src="https://user-images.githubusercontent.com/889538/44505766-c7c04b80-a6c0-11e8-8ab3-0eb4cbced1d3.png">

(Also the images in the email are huge - check the pdf below for the full preview)
[Doges On Trial Update.pdf](https://github.com/kleros/doges-on-trial/files/2312981/Doges.On.Trial.Update.pdf)

**Comment by clesaege** [comment]
About the challenge, it means you lost it. Other people can try to challenge it again. If the image stays 1 day unchallenged, it's accepted.
