### ISSUE TITLE
Suggestion - Instruction Clarity and Support

### ISSUE THREAD

**Issue by ssbramson** [kleros/doges-on-trial#5]
- The "Need MetaMask" page, we should include a small note about once you have logged into you Web3/MetaMask, to please "refresh" the page . 

- Once a user has Web3 enabled, none of the pages currently have the ability for a user to "contact" and/or "get support/FAQs", we might want to consider adding something similar to what is there on the "Web3 is needed" landing page.

**Comment by epiqueras** [comment]
Done.
